In [1]:
#Convolutional Neural Network on MNIST handwritten digit dataset

In [10]:
#importing libraries
import keras
from keras.models import Sequential
from keras.layers.core import Dense, Dropout, Activation, Flatten
from keras.layers.convolutional import Convolution2D, MaxPooling2D
from sklearn.model_selection import train_test_split
import pandas as pd
import numpy as np 

In [3]:
data = pd.read_csv('mnist.csv')

In [4]:
data.head()

label  pixel0  pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  \
0      1       0       0       0       0       0       0       0       0   
1      0       0       0       0       0       0       0       0       0   
2      1       0       0       0       0       0       0       0       0   
3      4       0       0       0       0       0       0       0       0   
4      0       0       0       0       0       0       0       0       0   

   pixel8    ...     pixel774  pixel775  pixel776  pixel777  pixel778  \
0       0    ...            0         0         0         0         0   
1       0    ...            0         0         0         0         0   
2       0    ...            0         0         0         0         0   
3       0    ...            0         0         0         0         0   
4       0    ...            0         0         0         0         0   

   pixel779  pixel780  pixel781  pixel782  pixel783  
0         0         0         0         0         0  
1         0         0         0         0         0  
2         0         0         0         0         0  
3         0         0         0         0         0  
4         0         0         0         0         0  

[5 rows x 785 columns]

In [6]:
#reshaping into 28X28 array
data.iloc[3,1:].values.reshape(28,28).astype('uint8')

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0, 220, 179,   6,   0,   0,   0,   0,
          0,   0,   0,   0,   9,  77,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  

In [7]:
#preprocessing data 

In [8]:
#Storing Pixel array in form length width and channel in df_x
df_x = data.iloc[:,1:].values.reshape(len(data),28,28,1)

#Storing the labels in y
y = data.iloc[:,0].values

In [11]:
#Converting labels to categorical features

df_y = keras.utils.to_categorical(y,num_classes=10)

In [12]:
df_x = np.array(df_x)
df_y = np.array(df_y)

In [14]:
#lables
y

array([1, 0, 1, ..., 7, 6, 9], dtype=int64)

In [15]:
#categorical labels
df_y

array([[ 0.,  1.,  0., ...,  0.,  0.,  0.],
       [ 1.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  1.,  0., ...,  0.,  0.,  0.],
       ..., 
       [ 0.,  0.,  0., ...,  1.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  1.]])

In [16]:
df_x.shape

(42000, 28, 28, 1)

In [17]:
#test train split

x_train, x_test, y_train, y_test = train_test_split(df_x,df_y,test_size=0.2,random_state=4)

In [25]:
#CNN model
model = Sequential()
model.add(Convolution2D(32,3,data_format='channels_last',activation='relu',input_shape=(28,28,1)))
model.add(MaxPooling2D(pool_size=(2,2)))
model.add(Flatten())
model.add(Dense(100))
model.add(Dropout(0.5))
model.add(Dense(10))
model.add(Activation('softmax'))
model.compile(loss='categorical_crossentropy', optimizer = 'adadelta', metrics = ['accuracy'])

In [26]:
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_3 (Conv2D)            (None, 26, 26, 32)        320       
_________________________________________________________________
max_pooling2d_2 (MaxPooling2 (None, 13, 13, 32)        0         
_________________________________________________________________
flatten_2 (Flatten)          (None, 5408)              0         
_________________________________________________________________
dense_3 (Dense)              (None, 100)               540900    
_________________________________________________________________
dropout_2 (Dropout)          (None, 100)               0         
_________________________________________________________________
dense_4 (Dense)              (None, 10)                1010      
_________________________________________________________________
activation_1 (Activation)    (None, 10)                0         
Total para

In [29]:
#fitting it with just 100 images for testing 

model.fit(x_train,y_train,validation_data=(x_test,y_test))

Train on 33600 samples, validate on 8400 samples
Epoch 1/10
33600/33600 [==============================] - 96s - loss: 7.7860 - acc: 0.5063 - val_loss: 4.4646 - val_acc: 0.7145
Epoch 2/10
33600/33600 [==============================] - 107s - loss: 3.8784 - acc: 0.7476 - val_loss: 1.6786 - val_acc: 0.8844
Epoch 3/10
33600/33600 [==============================] - 117s - loss: 1.7091 - acc: 0.8812 - val_loss: 1.0423 - val_acc: 0.9254
Epoch 4/10
33600/33600 [==============================] - 115s - loss: 1.0479 - acc: 0.9222 - val_loss: 0.7083 - val_acc: 0.9489
Epoch 5/10
33600/33600 [==============================] - 112s - loss: 0.7755 - acc: 0.9407 - val_loss: 0.5226 - val_acc: 0.9574
Epoch 6/10
33600/33600 [==============================] - 114s - loss: 0.6248 - acc: 0.9500 - val_loss: 0.4497 - val_acc: 0.9637
Epoch 7/10
33600/33600 [==============================] - 113s - loss: 0.5083 - acc: 0.9570 - val_loss: 0.3780 - val_acc: 0.9665
Epoch 8/10
33600/33600 [=========================

In [30]:
model.evaluate(x_test,y_test)

8384/8400 [============================>.] - ETA: 0s

[0.27073475346692977, 0.97261904761904761]

In [ ]:
#imporove accuracy by more epocs till the loss is almost same